version: '3.1'

services:

  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    # ports:
    # - 5432:5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    networks:
      - backend
  
  pgadmin4:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.admin
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 80
    # ports:
      # - 88:80
      # - 443:443
    
    volumes:
      - ./pgadmin4/pgadmin:/var/lib/pgadmin
    networks:
      - backend
